name: Run API_GATEWAY Jar

on:
  push:
    branches:
      -  main

jobs:
  api-gateway-run:
    runs-on: ubuntu-latest

    steps:

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          
      - name: Check java version
        run: java --version
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code is checkout or not
        run: ls -ltr

      - name: OSS Scan
        run: mvn ossindex:audit
        continue-on-error: true
        
      - name: Perfrom Goggle java formatter
        run: mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: Build Code And Create docker image
        run: mvn clean install docker:build
        
      - name: Re tag docker image
        run: docker tag dnyanyog.org/api-gateway:latest abhijeetnirphal/api-gateway:latest

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
           username: ${{secrets.DOCKER_REGISTRY_USER}}
           password: ${{secrets.DOCKER_REGISTRY_PAT}}

      - name: Push docker images
        run: docker push abhijeetnirphal/api-gateway:latest
        
      
