name: Run API_GATEWAY Jar

on:
  push:
    branches:
      -  main

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
     image: dnyanyog.org/maven-jdk:latest

    steps:
      - name: api-gateway
        run: echo "Hello World !!"
