name: Run API_GATEWAY Jar

on:
  push:
    branches:
      -  main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Run Service
        run: mvn clean install 
