name: Run API_GATEWAY Jar

on:
  push:
    branches:
      -  main

jobs:
  api-gateway-run:
    runs-on: ubuntu-latest

    steps:

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          
      - name: Check java version
        run: java --version
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code is checkout or not
        run: ls -ltr
  

      - name: Perfrom Goggle java formatter
        run: mvn com.spotify.fmt:fmt-maven-plugin:check
